client/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from client import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include('cms.urls', namespace='cms')),
    url(r'^domain/$', views.input_url, name='input_url'),
    url(r'^domain/form/$', views.form_url, name='form_url')
]

cms/urls.py
from django.conf.urls import url
from cms import views

urlpatterns = [
	url(r'^domain/$', views.domain_list, name='domain_list'),
	url(r'^domain/add/$', views.domain_edit, name='domain_add'),
	url(r'^domain/mod/(?P<domain_id>\d+)/$', views.domain_edit, name='domain_mod'),
	url(r'^domain/del/(?P<domain_id>\d+)/$', views.domain_del, name='domain_del'),
	url(r'^domain/add/file$', views.domain_add_byfile, name='domain_add_byfile'),
	url(r'^param/add/$', views.param_edit, name='param_add'),
	url(r'^param/mod/(?P<param_id>\d+)/$', views.param_edit, name='param_mod'),
	url(r'^param/del/(?P<param_id>\d+)/$', views.param_del, name='param_del'),
]

cms/models.py
from django.db import models

# Create your models here.
class Domain(models.Model):
	name = models.CharField('domain', max_length=255)
	ip = models.CharField('IP', max_length=255)

	def __str__(self):
		return self.name

class ConvertParam(models.Model):
	key = models.CharField('key', max_length=255)
	value = models.CharField('value', max_length=255)

	def __str__(self):
		return self.key;

cms/forms.py
from django.forms import ModelForm
from cms.models import Domain, ConvertParam


class DomainForm(ModelForm):
    class Meta:
        model = Domain
        fields = ('name', 'ip', )

class ConvertParamForm(ModelForm):
    class Meta:
        model = ConvertParam
        fields = ('key', 'value', )

client/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
import urllib
from urllib import parse,request
from cms.models import Domain,ConvertParam
from urllib.error import URLError

def input_url(request):
    return render(request, 'client/input_url.html')

def form_url(request):
    parse_url = parse.urlparse(request.POST['access_url'])

    domains = Domain.objects.all()
    parsed_ip = parse_url.netloc
    for domain in domains:
        if parsed_ip.find(domain.name) != -1 :
            parsed_ip = domain.ip
            break

    convert_params = ConvertParam.objects.all()
    parsed_params = parse.parse_qs(parse_url.query)
    for convert_param in convert_params:
        if convert_param.key in parsed_params:
            # initialize
            del parsed_params[convert_param.key][:]
            parsed_params[convert_param.key].append(convert_param.value)

    query_map = dict()
    for key in parsed_params.keys():
        query_map[key] = parsed_params[key][0]

    url = parse.urlunparse((parse_url[0],
                            parsed_ip,
                            parse_url[2],
                            parse_url[3],
                            parse.urlencode(query_map),
                            parse_url[5]))

    json = url + "\n"
    print("[DEBUG]:" + json)
    try:
        result = urllib.request.urlopen(url)
        json += result.read().decode("utf-8")
    except URLError as e:
        json += "{'error': '接続できませんでした'}"

    return HttpResponse(json, content_type='application/json; charset=UTF-8')

cms/views.py
from django.shortcuts import render, get_object_or_404, redirect

from cms.models import Domain, ConvertParam
from cms.forms import DomainForm, ConvertParamForm

import csv

# Create your views here.
def domain_list(request):
	domains = Domain.objects.all().order_by('id')
	params = ConvertParam.objects.all().order_by('id')
	return render(request,
					'cms/domain_list.html',
					{'domains': domains,
					 'params': params})

def domain_edit(request, domain_id=None):
	if domain_id:
		domain = get_object_or_404(Domain, pk=domain_id)
	else:
		domain = Domain()

	if request.method == 'POST':
		form = DomainForm(request.POST, instance=domain)
		if form.is_valid():
			domain = form.save(commit=False)
			domain.save()
			return redirect('cms:domain_list')
	else:
		form = DomainForm(instance=domain)

	return render(request, 'cms/domain_edit.html', dict(form=form, domain_id=domain_id))

def param_edit(request, param_id=None):
	if param_id:
		param = get_object_or_404(ConvertParam, pk=param_id)
	else:
		param = ConvertParam()

	if request.method == 'POST':
		form = ConvertParamForm(request.POST, instance=param)
		if form.is_valid():
			param = form.save(commit=False)
			param.save()
			return redirect('cms:domain_list')
	else:
		form = ConvertParamForm(instance=param)

	return render(request, 'cms/param_edit.html', dict(form=form, param_id=param_id))

def domain_del(request, domain_id):
	domain = get_object_or_404(Domain, pk=domain_id)
	domain.delete()
	return redirect('cms:domain_list')

def param_del(request, param_id):
	param = get_object_or_404(ConvertParam, pk=param_id)
	param.delete()
	return redirect('cms:domain_list')

def domain_add_byfile(request):
	# "domain", "ip"
	csv_file = request.POST['csv_file']
	reader = csv.reader(csv_file.strip().splitlines())
	for row in reader:
		print(row)
		domain = Domain()
		domain.name = row[0]
		domain.ip = row[1]
		domain.save()

	return redirect('cms:domain_list')

cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}My domains{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
		<script src="{% static 'js/jquery-3.1.1.slim.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
		<script src="{% static 'js/shortcut.js' %}"></script>
		{% block extrahead %}{% endblock %}
	</head>
<body>
	<div class="container">
	 {% block content %}
		{{ content }}
	{% endblock %}
	</div>
</body>
</html>

cms/templates/client/input_url.html
{% extends "base.html" %}

{% block title %}URL入力{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
<script>
$(function() {
  $("#base_url").keyup(function() {
      $("#query").empty()
      var url = $(this).val();
      var queries = url.split('?')[1].split('&');
      for(var query of queries) {
        param = query.split('=')[0];
        val = query.split('=')[1];
        $("#query").append('<div><label>' + param + '</label><input type=text value="' + val + '"/></div></br>');
      }
  });

  shortcut.add("Ctrl+I",function() {
      $("#base_url").focus();
  });


});
</script>
{% endblock %}

{% block content %}
<h3 class="page-header">URL入力</h3>
<form action="{% url 'form_url' %}" method="post" class="form-horizontal" role="form" target="_blank">
  {% csrf_token %}
  <div class="form-group">
    <div class="col-sm-10">
      <input id="base_url" class="form-control" type="url" name="access_url" placeholder="input url (Ctrl+I)"/>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">送信</button>
    </div>
  </div>
</form>
<div id="query">
</div>
<a href="{% url 'cms:domain_list' %}" target="_blank">Table</a>
{% endblock content %}

cms/templates/cms/domain_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}ドメインの編集{% endblock title %}

{% block content %}
    <h3 class="page-header">ドメインの編集</h3>
    {% if domain_id %}
    <form action="{% url 'cms:domain_mod' domain_id=domain_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:domain_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      <!-- formで送られてきた内容を展開 -->
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:domain_list' %}" class="btn btn-default btn-sm">戻る</a>
    <h3>ドメインをcsvで追加</h3>
    <form action="{% url 'cms:domain_add_byfile' %}" method="post" class="form-horizontal" role="form">
      {% csrf_token %}
      <div class="form-group">
        <label class="col-lg-2">csv入力</label>
        <div class="col-lg-10">
          <textarea type="text" placeholder='"google.com", "127.0.0.1"' name="csv_file" cols="100" rows="15"></textarea>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10">
          <button type="submit" class="btn">送信</button>
        </div>
      </div>
    </form>
{% endblock content %}

cms/templates/cms/domain_list.html
{% extends "base.html" %}

{% block title %}ドメイン一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">変換ドメインの一覧</h3>
    <a href="{% url 'cms:domain_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>ドメイン名</th>
          <th>IPアドレス</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for domain in domains %}
        <tr>
          <td>{{ domain.id }}</td>
          <td>{{ domain.name }}</td>
          <td>{{ domain.ip }}</td>
          <td>
            <a href="{% url 'cms:domain_mod' domain_id=domain.id %}" class="btn btn-default btn-sm">修正</a>
            <a href="{% url 'cms:domain_del' domain_id=domain.id %}" class="btn btn-default btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <h3 class="page-header">変換パラメータ一覧</h3>
    <a href="{% url 'cms:param_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>パラメータ名</th>
          <th>Value</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for param in params %}
        <tr>
          <td>{{ param.id }}</td>
          <td>{{ param.key }}</td>
          <td>{{ param.value }}</td>
          <td>
            <a href="{% url 'cms:param_mod' param_id=param.id %}" class="btn btn-default btn-sm">修正</a>
            <a href="{% url 'cms:param_del' param_id=param.id %}" class="btn btn-default btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}

cms/templates/cms/param_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}パラメータの編集{% endblock title %}

{% block content %}
    <h3 class="page-header">パラメータの編集</h3>
    {% if param_id %}
    <form action="{% url 'cms:param_mod' param_id=param_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:param_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      <!-- formで送られてきた内容を展開 -->
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
{% endblock content %}